version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: sintetica
      POSTGRES_DB: girardot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://user:sintetica@db:5432/girardot
      CORS_ORIGINS: http://localhost:5173
      SECRET_KEY: clavesintetica
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "-m", "app.main"]

volumes:
  pgdata:
