[mypy]
python_version = 3.11
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
disallow_untyped_defs = False
check_untyped_defs = True
no_implicit_optional = True
pretty = True

plugins = sqlalchemy.ext.mypy.plugin
exclude = migrations/.*

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-tests.*]
disable_error_code = var-annotated
ignore_missing_imports = True

[mypy-pytest]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-uvicorn.*]
ignore_missing_imports = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-app.routers.*]
disable_error_code = no-redef

[mypy-scripts.*]
ignore_errors = True
